src/main/java/org/entando/entando/plugins/jpsolr/apsadmin/portal/specialwidget/FacetNavTreeWidgetAction.java
/*
 * Copyright 2015-Present Entando Inc. (http://www.entando.com) All rights reserved.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to deal
 * in the Software without restriction, including without limitation the rights
 * to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
 * copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
 * THE SOFTWARE.
 */
package org.entando.entando.plugins.jpsolr.apsadmin.portal.specialwidget;

import java.util.Collection;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import com.agiletec.aps.system.ApsSystemUtils;
import com.agiletec.aps.system.common.tree.ITreeNode;
import com.agiletec.aps.system.common.tree.ITreeNodeManager;
import com.agiletec.apsadmin.system.ITreeAction;
import com.agiletec.apsadmin.system.ITreeNodeBaseActionHelper;
import org.entando.entando.plugins.jpsolr.aps.system.JpSolrSystemConstants;
import org.entando.entando.plugins.jpsolr.apsadmin.portal.specialwidget.util.FacetNavWidgetHelper;

/**
 * @author E.Santoboni
 */
public class FacetNavTreeWidgetAction extends FacetNavResultWidgetAction implements ITreeAction {
	
	@Override
	public void validate() {
		super.validate();
		try {
			this.validateFacets();
		} catch (Throwable t) {
			ApsSystemUtils.logThrowable(t, this, "validate");
		}
	}
	
	protected void validateFacets() {
		List<String> facetCodes = this.getFacetRootCodes();
		for (String facetCode : facetCodes) {
			if (null == this.getFacet(facetCode)) {
				String[] args = { facetCode };
				String fieldName = JpSolrSystemConstants.FACET_ROOTS_WIDGET_PARAM_NAME;
				this.addFieldError(fieldName, this.getText("message.facetNavWidget.facets.notValid", args));
			}
		}
	}
	
	/**
	 * Prepare action with the parameters contained in showlet.
	 */
	@Override
	protected void initSpecialParams() {
		super.initSpecialParams();
		if (null != this.getWidget().getConfig()) {
			String configParamName = JpSolrSystemConstants.FACET_ROOTS_WIDGET_PARAM_NAME;
			String facetsParam = this.getWidget().getConfig().getProperty(configParamName);
			this.setFacetRootNodes(facetsParam);
		}
	}
	
	/**
	 * Add a facet to the associated facet nodes
	 * @return The code describing the result of the operation.
	 */
	public String joinFacet() {
		try {
			this.createValuedShowlet();
			if (this.isValidFacet()) {
				String facetCode = this.getFacetCode();
				List<String> facetCodes = this.getFacetRootCodes();
				ITreeNode facet = this.getTreeNodeManager().getNode(this.getFacetCode());
				if (facet != null && !facet.getCode().equals(facet.getParentCode()) && !facetCodes.contains(facetCode)) {//se esiste, non è la Home e non è 
					facetCodes.add(facetCode);
					String facetsFilter = FacetNavWidgetHelper.concatStrings(facetCodes, ",");
					String configParamName = JpSolrSystemConstants.FACET_ROOTS_WIDGET_PARAM_NAME;
					this.getWidget().getConfig().setProperty(configParamName, facetsFilter);
					this.setFacetRootNodes(facetsFilter);
				}
			}
		} catch (Throwable t) {
			ApsSystemUtils.logThrowable(t, this, "joinFacet");
			return FAILURE;
		}
		return SUCCESS;
	}
	
	/**
	 * Remove a facet from the associated facet nodes
	 * @return The code describing the result of the operation.
	 */
	public String removeFacet() {
		try {
			this.createValuedShowlet();
			String facetCode = this.getFacetCode();
			List<String> facetCodes = this.getFacetRootCodes();
			if (facetCode != null) {
                facetCodes.remove(facetCode);
				String facetsFilter = FacetNavWidgetHelper.concatStrings(facetCodes, ",");
				String configParamName = JpSolrSystemConstants.FACET_ROOTS_WIDGET_PARAM_NAME;
				this.getWidget().getConfig().setProperty(configParamName, facetsFilter);
				this.setFacetRootNodes(facetsFilter);
			}
		} catch (Throwable t) {
			ApsSystemUtils.logThrowable(t, this, "removeFacet");
			return FAILURE;
		}
		return SUCCESS;
	}

	/**
	 * Returns true if the facet is valid
	 * @return true if the facet is valid
	 */
	private boolean isValidFacet() {
		String facetCode = this.getFacetCode();
		return (facetCode != null && this.getFacet(facetCode) != null);
	}

	public ITreeNode getFacetRoot() {
		return this.getTreeNodeManager().getRoot();
	}

	public ITreeNode getFacet(String facetCode) {
		return this.getTreeNodeManager().getNode(facetCode);
	}

	public String getFacetCode() {
		return facetCode;
	}
	public void setFacetCode(String facetCode) {
		this.facetCode = facetCode;
	}

	public List<String> getFacetRootCodes() {
		String facetsParam = this.getFacetRootNodes();
		return FacetNavWidgetHelper.splitValues(facetsParam, ",");
	}

	public String getFacetRootNodes() {
		return facetRootNodes;
	}
	public void setFacetRootNodes(String facetRootNodes) {
		this.facetRootNodes = facetRootNodes;
	}
	
	@Override
	public String buildTree() {
		Set<String> targets = this.getTreeNodesToOpen();
		try {
			this.createValuedShowlet();
			String marker = this.getTreeNodeActionMarkerCode();
			if (null != marker) {
				if (marker.equalsIgnoreCase(ACTION_MARKER_OPEN)) {
					targets = this.getTreeHelper().checkTargetNodes(this.getTargetNode(), targets, this.getNodeGroupCodes());
				} else if (marker.equalsIgnoreCase(ACTION_MARKER_CLOSE)) {
					targets = this.getTreeHelper().checkTargetNodesOnClosing(this.getTargetNode(), targets, this.getNodeGroupCodes());
				}
			}
			this.setTreeNodesToOpen(targets);
		} catch (Throwable t) {
			ApsSystemUtils.logThrowable(t, this, "buildTree");
			return FAILURE;
		}
		return SUCCESS;
	}
	
	@Override
	public ITreeNode getShowableTree() {
		ITreeNode node = null;
		try {
			ITreeNode allowedTree = this.getAllowedTreeRootNode();
			node = this.getTreeHelper().getShowableTree(this.getTreeNodesToOpen(), allowedTree, this.getNodeGroupCodes());
		} catch (Throwable t) {
			ApsSystemUtils.logThrowable(t, this, "getShowableTree");
		}
		return node;
	}
	
	@Override
	public ITreeNode getAllowedTreeRootNode() {
		ITreeNode node = null;
		try {
			node = this.getTreeHelper().getAllowedTreeRoot(this.getNodeGroupCodes());
		} catch (Throwable t) {
			ApsSystemUtils.logThrowable(t, this, "getAllowedTreeRootNode");
		}
		return node;
	}
	
	/**
	 * Return the allowed codes of the group of the nodes to manage.
	 * This method has to be extended if the helper manage tree nodes with authority.
	 * @return The allowed group codes.
	 */
	protected Collection<String> getNodeGroupCodes() {
		return null;
	}
	
	public String getTargetNode() {
		return targetNode;
	}
	public void setTargetNode(String targetNode) {
		this.targetNode = targetNode;
	}
	
	public Set<String> getTreeNodesToOpen() {
		return treeNodesToOpen;
	}
	public void setTreeNodesToOpen(Set<String> treeNodesToOpen) {
		this.treeNodesToOpen = treeNodesToOpen;
	}
	
	public String getTreeNodeActionMarkerCode() {
		return treeNodeActionMarkerCode;
	}
	public void setTreeNodeActionMarkerCode(String treeNodeActionMarkerCode) {
		this.treeNodeActionMarkerCode = treeNodeActionMarkerCode;
	}
	
	protected ITreeNodeManager getTreeNodeManager() {
		return treeNodeManager;
	}
	public void setTreeNodeManager(ITreeNodeManager treeNodeManager) {
		this.treeNodeManager = treeNodeManager;
	}
	
	protected ITreeNodeBaseActionHelper getTreeHelper() {
		return treeHelper;
	}
	public void setTreeHelper(ITreeNodeBaseActionHelper treeHelper) {
		this.treeHelper = treeHelper;
	}
	
	private String facetCode;
	private String facetRootNodes;
	
	private String targetNode;
	private Set<String> treeNodesToOpen = new HashSet<>();
	
	private String treeNodeActionMarkerCode;

	private transient ITreeNodeManager treeNodeManager;
	
	private transient ITreeNodeBaseActionHelper treeHelper;

}

src/main/webapp/WEB-INF/plugins/jpsolr/aps/jsp/widgets/jpsolr_facetResults.jsp
<%@ taglib prefix="wpfp" uri="/jpsolr-core" %>
<%@ taglib prefix="wp" uri="/aps-core" %>
<%@ taglib prefix="wpcms" uri="/jacms-aps-core" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<wp:headInfo type="CSS" info="../../plugins/jpsolr/jpsolr.css"/>
<div class="jpsolr">

<h2><wp:i18n key="jpsolr_TITLE_FACET_RESULTS" /></h2>

<%-- NOTA : l'attributo "executeExtractRequiredFacets" è a false perchè si presume che sia inserita la showlet facetNavTree prima --%>
<wpfp:facetNavResult requiredFacetsParamName="requiredFacets"
	resultParamName="contentList" executeExtractRequiredFacets="false" breadCrumbsParamName="breadCrumbs" />

<c:if test="${breadCrumbs != null && !empty breadCrumbs}">
	<p><wp:i18n key="SEARCHED_FOR" />:</p>
	<ul class="jpsolr_filterlist">
		<c:forEach var="item" items="${breadCrumbs}" varStatus="itemStatus">
		<li>
			<c:forEach var="breadCrumb" items="${item.breadCrumbs}" varStatus="status">
				<c:if test="${!status.first}">
					<c:choose>
						<c:when test="${breadCrumb == item.requiredFacet}">
							<span class="jpfacetfilter jpsolr_requiredFacet"><wpfp:facetNodeTitle facetNodeCode="${breadCrumb}" /></span>
							<c:set var="currentNodeTitle"><wpfp:facetNodeTitle facetNodeCode="${breadCrumb}" /></c:set>
						</c:when>
						<c:when test="${breadCrumb == item.facetRoot}">
							<span class="jpfacetfilter jpsolr_facetRoot"><wpfp:facetNodeTitle facetNodeCode="${item.facetRoot}" /></span>
							<c:set var="currentNodeTitle"><wpfp:facetNodeTitle facetNodeCode="${item.facetRoot}" /></c:set>
						</c:when>
						<c:otherwise>
							<a title="<wp:i18n key="jpsolr_REMOVE_FILTER" />: <wpfp:facetNodeTitle facetNodeCode="${breadCrumb}" />" class="jpfacetfilter" href="<wp:url><wpfp:urlPar name="selectedNode" ><c:out value="${breadCrumb}" /></wpfp:urlPar><c:forEach var="requiredFacet" items="${requiredFacets}" varStatus="statusInternal"><wpfp:urlPar name="facetNode_${statusInternal.count}" ><c:out value="${requiredFacet}" /></wpfp:urlPar></c:forEach></wp:url>">
								<wpfp:facetNodeTitle facetNodeCode="${breadCrumb}" />
							</a>
							<c:set var="currentNodeTitle"><wpfp:facetNodeTitle facetNodeCode="${breadCrumb}" /></c:set>
						</c:otherwise>
					</c:choose>

					<c:if test="${!status.last}">&#32;/&#32;</c:if>
					<c:if test="${status.last}"></c:if>
				</c:if>

			</c:forEach>
			<span class="noscreen">|</span>&#32;<a class="jpsolrfilterremove" title="<wp:i18n key="jpsolr_REMOVE_FILTER" />:&#32;<c:out value="${currentNodeTitle}" />" href="<wp:url><c:forEach var="requiredFacet" items="${requiredFacets}" varStatus="statusInternal"><wpfp:urlPar name="facetNode_${statusInternal.count}" ><c:out value="${requiredFacet}" /></wpfp:urlPar></c:forEach><c:forEach var="breadCrumb" items="${item.breadCrumbs}" varStatus="status2"><wpfp:urlPar name="facetNodeToRemove_${status2.count}" ><c:out value="${breadCrumb}" /></wpfp:urlPar></c:forEach></wp:url>">
			<img src="<wp:resourceURL />plugins/jpsolr/static/img/edit-delete.png" alt="<wp:i18n key="jpsolr_REMOVE_FILTER" />" /></a>
			<%-- <c:if test="${!itemStatus.last}">&#32;|&#32;</c:if> --%>
		</li>
		</c:forEach>
	</ul>
</c:if>

<c:choose>
	<c:when test="${empty contentList}">
		<p><em><wp:i18n key="SEARCH_NOTHING_FOUND" /></em></p>
	</c:when>
	<c:otherwise>

		<wp:pager listName="contentList" objectName="groupContent" max="10" pagerIdFromFrame="true" >

			<p><em><wp:i18n key="SEARCH_RESULTS_INTRO" />&#32;<c:out value="${groupContent.size}" />&#32;<wp:i18n key="SEARCH_RESULTS_OUTRO" />&#32;[<c:out value="${groupContent.begin + 1}" /> &ndash; <c:out value="${groupContent.end + 1}" />]:</em></p>
			<ol class="pureSize">
				<c:forEach var="contentId" items="${contentList}" begin="${groupContent.begin}" end="${groupContent.end}">
					<li><wpcms:content contentId="${contentId}" modelId="list" /></li>
				</c:forEach>
			</ol>

			<c:if test="${groupContent.size > groupContent.max}">
				<div>
					<p class="paginazione">
						<c:choose>
						<c:when test="${'1' == groupContent.currItem}">&laquo;&#32;<wp:i18n key="PREV" /></c:when>
						<c:otherwise><a href="<wp:url paramRepeat="true" >
						<wp:parameter name="${groupContent.paramItemName}" ><c:out value="${groupContent.prevItem}"/></wp:parameter><c:forEach var="requiredFacet" items="${requiredFacets}" varStatus="status"><wp:parameter name="facetNode_${status.count}" ><c:out value="${requiredFacet}" /></wp:parameter></c:forEach></wp:url>">&laquo;&#32;<wp:i18n key="PREV" /></a></c:otherwise>
						</c:choose>
						<c:forEach var="item" items="${groupContent.items}">
							<c:choose>
							<c:when test="${item == groupContent.currItem}">&#32;[<c:out value="${item}"/>]&#32;</c:when>
							<c:otherwise>&#32;<a href="<wp:url paramRepeat="true" ><wp:parameter name="${groupContent.paramItemName}" ><c:out value="${item}"/></wp:parameter><c:forEach var="requiredFacet" items="${requiredFacets}" varStatus="status"><wp:parameter name="facetNode_${status.count}" ><c:out value="${requiredFacet}" /></wp:parameter></c:forEach></wp:url>"><c:out value="${item}"/></a>&#32;</c:otherwise>
							</c:choose>
						</c:forEach>
						<c:choose>
						<c:when test="${groupContent.maxItem == groupContent.currItem}"><wp:i18n key="NEXT" />&#32;&raquo;</c:when>
						<c:otherwise><a href="<wp:url paramRepeat="true" ><wp:parameter name="${groupContent.paramItemName}" ><c:out value="${groupContent.nextItem}"/></wp:parameter><c:forEach var="requiredFacet" items="${requiredFacets}" varStatus="status"><wp:parameter name="facetNode_${status.count}" ><c:out value="${requiredFacet}" /></wp:parameter></c:forEach></wp:url>"><wp:i18n key="NEXT" />&#32;&raquo;</a></c:otherwise>
						</c:choose>
					</p>
				</div>
			</c:if>

		</wp:pager>

	</c:otherwise>
</c:choose>
</div>

src/main/webapp/WEB-INF/plugins/jpsolr/aps/jsp/widgets/jpsolr_facetTree.jsp
<%@ taglib prefix="wpfp" uri="/jpsolr-core" %>
<%@ taglib prefix="wp" uri="/aps-core" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core"%>
<wp:headInfo type="CSS" info="../../plugins/jpsolr/static/css/jpsolr.css"/>
<div class="jpsolr">
	<h2 class="title"><wp:i18n key="jpsolr_TITLE_TREE" /></h2>
	<wpfp:facetNavTree requiredFacetsParamName="requiredFacets" facetsTreeParamName="facetsForTree" />
	<c:set var="occurrences" value="${occurrences}" scope="request" />
	<c:forEach var="facetRoot" items="${facetsForTree}">
		<h3><wpfp:facetNodeTitle facetNodeCode="${facetRoot.code}" /></h3>
		<c:choose>
			<c:when test="${occurrences[facetRoot.code] != null && !(empty occurrences[facetRoot.code])}">
				<ul>
					<c:forEach var="facetNode" items="${facetRoot.children}">
						<c:if test="${occurrences[facetNode.code] != null}">
							<li>
								<a href="<wp:url><wp:parameter name="selectedNode" ><c:out value="${facetNode.code}" /></wp:parameter>
									<c:forEach var="requiredFacet" items="${requiredFacets}" varStatus="status">
										<wpfp:urlPar name="facetNode_${status.count}" ><c:out value="${requiredFacet}" /></wpfp:urlPar>
									</c:forEach>
									</wp:url>"><wpfp:facetNodeTitle facetNodeCode="${facetNode.code}" /></a>&#32;<abbr class="jpsolr_tree_occurences" title="<wp:i18n key="jpsolr_OCCURRENCES_FOR" />&#32;<wpfp:facetNodeTitle facetNodeCode="${facetNode.code}" />:&#32;<c:out value="${occurrences[facetNode.code]}" />"><c:out value="${occurrences[facetNode.code]}" /></abbr>
								<wpfp:hasToOpenFacetNode facetNodeCode="${facetNode.code}" requiredFacets="${requiredFacets}" occurrences="${occurrences}" >
									<c:set var="currFacetRoot" value="${facetNode}" scope="request" />
									<c:import url="/WEB-INF/plugins/jpsolr/aps/jsp/widgets/inc/inc_facetNavTree.jsp" />
								</wpfp:hasToOpenFacetNode>
							</li>
						</c:if>
					</c:forEach>
				</ul>
			</c:when>
			<c:otherwise>
				<p><abbr title="<wp:i18n key="jpsolr_EMPTY_TAG" />:&#32;<wpfp:facetNodeTitle facetNodeCode="${facetRoot.code}" escapeXml="true" />">&ndash;</abbr></p>
			</c:otherwise>
		</c:choose>
	</c:forEach>
</div>